=== Rishi-git5230/MetaData_Modeler-Service/src/main/java/com/systech/hawkeye/Implementation/v1/userSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "PrimaryProductID": {
      "type": "object",
      "properties": {
        "PrimaryIdentification": {
          "type": "object",
          "properties": {
            "ProductID": {
              "type": "string"
            },
            "ProductIDType": {
              "type": "string"
            }
          },
          "required": [
            "ProductID",
            "ProductIDType"
          ]
        }
      },
      "required": [
        "PrimaryIdentification"
      ]
    },
    "Product Name": {
      "type": "string"
    },
    "Product Description": {
      "type": "string"
    },
    "MinimumTemperature": {
      "type": "string"
    },
    "MaximumTemperature": {
      "type": "string"
    },
    "TemperatureUoM": {
      "type": "string"
    },
    "SensitiveToLight": {
      "type": "boolean"
    },
    "ShelfLife": {
      "type": "integer"
    },
    "ShelfLifeUoM": {
      "type": "string"
    },
    "AdditionalProductIDs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    },
    "PharmaInfo": {
      "type": "object",
      "properties": {
        "PrimaryProductID": {
          "type": "string"
        },
        "Dosage": {
          "type": "string"
        },
        "Strength": {
          "type": "string"
        },
        "PackageSize": {
          "type": "string"
        },
        "Classification": {
          "type": "string"
        },
        "GenericName": {
          "type": "string"
        },
        "ControlledSubstance": {
          "type": "string"
        },
        "MAHID": {
          "type": "string"
        },
        "MAHIDType": {
          "type": "string"
        },
        "ActiveIngradient": {
          "type": "string"
        },
        "ManufacturedBy": {
          "type": "string"
        }
      },
      "required": [
        "PrimaryProductID",
        "Dosage",
        "Strength",
        "PackageSize",
        "Classification",
        "GenericName",
        "ControlledSubstance",
        "MAHID",
        "MAHIDType",
        "ActiveIngradient",
        "ManufacturedBy"
      ]
    },
    "TargetMarket": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "TargetMarketCoutryCode": {
              "type": "string"
            },
            "TMLanguage": {
              "type": "string"
            },
            "LabelImage": {
              "type": "string"
            },
            "Type": {
              "type": "string"
            },
            "ManufacturerID": {
              "type": "string"
            },
            "ManufacturerIDType": {
              "type": "string"
            }
          },
          "required": [
            "TargetMarketCoutryCode",
            "TMLanguage",
            "LabelImage",
            "Type",
            "ManufacturerID",
            "ManufacturerIDType"
          ]
        },
        {
          "type": "object",
          "properties": {
            "TargetMarketCoutryCode": {
              "type": "string"
            },
            "TMLanguage": {
              "type": "string"
            },
            "LabelImage": {
              "type": "string"
            },
            "Type": {
              "type": "string"
            },
            "ManufacturerID": {
              "type": "string"
            },
            "ManufacturerIDType": {
              "type": "string"
            }
          },
          "required": [
            "TargetMarketCoutryCode",
            "TMLanguage",
            "LabelImage",
            "Type",
            "ManufacturerID",
            "ManufacturerIDType"
          ]
        },
        {
          "type": "object",
          "properties": {
            "TargetMarketCoutryCode": {
              "type": "string"
            },
            "TMLanguage": {
              "type": "string"
            },
            "LabelImage": {
              "type": "string"
            },
            "Type": {
              "type": "string"
            },
            "ManufacturerID": {
              "type": "string"
            },
            "ManufacturerIDType": {
              "type": "string"
            }
          },
          "required": [
            "TargetMarketCoutryCode",
            "TMLanguage",
            "LabelImage",
            "Type",
            "ManufacturerID",
            "ManufacturerIDType"
          ]
        }
      ]
    },
    "PackagingInfo": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "packaging code": {
              "type": "string"
            },
            "packaging code type": {
              "type": "string"
            },
            "UoM": {
              "type": "string"
            },
            "ChildItenCount": {
              "type": "string"
            },
            "PackagingRatio": {
              "type": "string"
            }
          },
          "required": [
            "packaging code",
            "packaging code type",
            "UoM",
            "ChildItenCount",
            "PackagingRatio"
          ]
        },
        {
          "type": "object",
          "properties": {
            "packaging code": {
              "type": "string"
            },
            "packaging code type": {
              "type": "string"
            },
            "UoM": {
              "type": "string"
            },
            "ChildItenCount": {
              "type": "string"
            },
            "PackagingRatio": {
              "type": "string"
            }
          },
          "required": [
            "packaging code",
            "packaging code type",
            "UoM",
            "ChildItenCount",
            "PackagingRatio"
          ]
        },
        {
          "type": "object",
          "properties": {
            "packaging code": {
              "type": "string"
            },
            "packaging code type": {
              "type": "string"
            },
            "UoM": {
              "type": "string"
            },
            "ChildItenCount": {
              "type": "string"
            },
            "PackagingRatio": {
              "type": "string"
            }
          },
          "required": [
            "packaging code",
            "packaging code type",
            "UoM",
            "ChildItenCount",
            "PackagingRatio"
          ]
        },
        {
          "type": "object",
          "properties": {
            "packaging code": {
              "type": "string"
            },
            "packaging code type": {
              "type": "string"
            },
            "UoM": {
              "type": "string"
            },
            "ChildItenCount": {
              "type": "string"
            },
            "PackagingRatio": {
              "type": "string"
            }
          },
          "required": [
            "packaging code",
            "packaging code type",
            "UoM",
            "ChildItenCount",
            "PackagingRatio"
          ]
        }
      ]
    },
    "Status": {
      "type": "string"
    }
  },
  "required": [
    "PrimaryProductID",
    "Product Name",
    "Product Description",
    "MinimumTemperature",
    "MaximumTemperature",
    "TemperatureUoM",
    "SensitiveToLight",
    "ShelfLife",
    "ShelfLifeUoM",
    "AdditionalProductIDs",
    "PharmaInfo",
    "TargetMarket",
    "PackagingInfo",
    "Status"
  ]
}

=== Rishi-git5230/MetaData_Modeler-Service/validated_jsons/validated_1729548944863_2e37c7b0-7f96-4cfd-b735-02c91f5fcdb3.json
{
    "PrimaryProductID": {
      "PrimaryIdentification": {
        "ProductID": "11523-0007-1",
        "ProductIDType": ""
      }
    },
    "Product Name": "Claritin",
    "Product Description": "1 BLISTER PACK in 1 CARTON (11523-0007-1)  / 10 TABLET in 1 BLISTER PACK",
    "MinimumTemperature": "30.5",
    "MaximumTemperature": "35.5",
    "TemperatureUoM": "celsius",
    "SensitiveToLight": true,
    "ShelfLife": 3,
    "ShelfLifeUoM": "year",
    "AdditionalProductIDs": [
      {
        "name": "demo" 
      },
      {
        "name": "demo1"
      }
    ],
    "PharmaInfo": {
      "PrimaryProductID": "11523-0007-1",
      "Dosage": "Tablet",
      "Strength": "10mg",
      "PackageSize": "10",
      "Classification": "",
      "GenericName": "loratadine",
      "ControlledSubstance": "No",
      "MAHID": "1234568929292",
      "MAHIDType": "GLN",
      "ActiveIngradient": "LORATADINE",
      "ManufacturedBy": "MAH, CMO"
    },
    "TargetMarket": [
      {
        "TargetMarketCoutryCode": "US",
        "TMLanguage": "EN",
        "LabelImage": "binary",
        "Type": "OTCDrug",
        "ManufacturerID": "1234568929292",
        "ManufacturerIDType": "GLN"
      },
      {
        "TargetMarketCoutryCode": "US",
        "TMLanguage": "EN",
        "LabelImage": "binary",
        "Type": "OTCDrug",
        "ManufacturerID": "22003389791234",
        "ManufacturerIDType": "GLN"
      },
      {
        "TargetMarketCoutryCode": "US",
        "TMLanguage": "EN",
        "LabelImage": "binary",
        "Type": "OTCDrug",
        "ManufacturerID": "8382924",
        "ManufacturerIDType": "DUNS"
      }
    ],
    "PackagingInfo": [
      {
        "packaging code": "12345678901234",
        "packaging code type": "GTIN14",
        "UoM": "Each",
        "ChildItenCount": "",
        "PackagingRatio": ""
      },
      {
        "packaging code": "12345678901235",
        "packaging code type": "GTIN14",
        "UoM": "InnerPack",
        "ChildItenCount": "10",
        "PackagingRatio": ""
      },
      {
        "packaging code": "12345678901236",
        "packaging code type": "GTIN14",
        "UoM": "Case",
        "ChildItenCount": "20",
        "PackagingRatio": ""
      },
      {
        "packaging code": "12345678901237",
        "packaging code type": "GTIN14",
        "UoM": "Pallet",
        "ChildItenCount": "100",
        "PackagingRatio": ""
      }
    ],
    "Status": ""
  }
